id: arcgis-rest-service-directory-traversal

info:
  name: Arcgis REST 服务目录浏览
  author: SleepingBag945
  severity: medium
  description: |-
    ArcGIS REST 服务目录为系统中所有的 ArcGIS Server Web 服务以及可通过 REST 执行的操作提供了一种基于 HTML 的可浏览的表现方式。ArcGIS REST 服务目录会暴露系统发布的服务，通过点Web界面上的链接可以获取到系统服务敏感数据。当不希望用户浏览系统中的服务列表、在 Web 搜索中查找系统中的服务或通过 HTML 表单请求系统中的服务时，建议在生产系统中禁用服务目录功能。
    FOFA: title="ArcGIS"
  reference:
    - https://cloud.tencent.com/developer/article/2149231

http:
  - raw:
      - |
        GET /arcgis/rest/services HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Folder: /"
        part: body
      - type: word
        words:
          - "ArcGIS REST Services Directory"
        part: body